/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserInfoRouteImport } from './routes/user-info'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteVotingIdRouteImport } from './routes/vote.$votingId'

const UserInfoRoute = UserInfoRouteImport.update({
  id: '/user-info',
  path: '/user-info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteVotingIdRoute = VoteVotingIdRouteImport.update({
  id: '/vote/$votingId',
  path: '/vote/$votingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user-info': typeof UserInfoRoute
  '/vote/$votingId': typeof VoteVotingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user-info': typeof UserInfoRoute
  '/vote/$votingId': typeof VoteVotingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user-info': typeof UserInfoRoute
  '/vote/$votingId': typeof VoteVotingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/user-info' | '/vote/$votingId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/user-info' | '/vote/$votingId'
  id: '__root__' | '/' | '/user-info' | '/vote/$votingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserInfoRoute: typeof UserInfoRoute
  VoteVotingIdRoute: typeof VoteVotingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-info': {
      id: '/user-info'
      path: '/user-info'
      fullPath: '/user-info'
      preLoaderRoute: typeof UserInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$votingId': {
      id: '/vote/$votingId'
      path: '/vote/$votingId'
      fullPath: '/vote/$votingId'
      preLoaderRoute: typeof VoteVotingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserInfoRoute: UserInfoRoute,
  VoteVotingIdRoute: VoteVotingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
