name: Test Native ARM Runner

on:
  workflow_dispatch:

jobs:
  test-arm-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Show architecture
        run: |
          uname -a
          uname -m

      - name: CPU info
        run: |
          lscpu